
server {
    listen 80;
    root /usr/share/nginx/html_app;
    index index.html;

    location /funcionarios {
        proxy_pass http://localhost:3000/funcionarios;
        proxy_set_header Host localhost;
        add_header Access-Control-Allow-Origin *;
    }

    location /estoque {
        proxy_pass http://localhost:3000/estoque;
        proxy_set_header Host localhost;
        add_header Access-Control-Allow-Origin *;
    }

    location /movimentacoes {
        proxy_pass http://localhost:3000/movimentacoes;
        proxy_set_header Host localhost;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
